// GENERATED by scripts/art/build-art.ts — do not edit by hand.
export const ART_DIMS: Record<string, { w: number; h: number; widths: number[] }> = {
  "free-huey-1968": {
    "w": 640,
    "h": 810,
    "widths": [
      640,
      1280
    ]
  },
  "honor-king-1968": {
    "w": 640,
    "h": 958,
    "widths": [
      640,
      1280
    ]
  },
  "mpla-anniversary-1975": {
    "w": 640,
    "h": 817,
    "widths": [
      640,
      1280
    ]
  },
  "young-lords-1971": {
    "w": 640,
    "h": 996,
    "widths": [
      640,
      1280
    ]
  },
  "negro-exposition-1940": {
    "w": 640,
    "h": 981,
    "widths": [
      640,
      1280
    ]
  },
  "naacp-broadside-1922": {
    "w": 640,
    "h": 887,
    "widths": [
      640,
      1280
    ]
  }
};
