// Pure helpers for the art pipeline — everything here is unit-testable
// without network or sharp.

export type ArtDims = { w: number; h: number; widths: number[] };

export const WIDTHS = [640, 1280];

export function searchUrl(objectNumber: string, apiKey: string): string {
  const q = encodeURIComponent(`"${objectNumber}" AND unit_code:NMAAHC`);
  return `https://api.si.edu/openaccess/api/v1.0/search?api_key=${apiKey}&rows=5&q=${q}`;
}

export function idsUrl(idsId: string, max: number): string {
  return `https://ids.si.edu/ids/deliveryService?id=${encodeURIComponent(idsId)}&max=${max}`;
}

export function variantFile(id: string, width: number): string {
  return `${id}-${width}.webp`;
}

type SearchRow = {
  content?: {
    descriptiveNonRepeating?: { online_media?: { media?: { idsId?: string }[] } };
    freetext?: { identifier?: { content?: string }[] };
  };
};

export function pickIdsId(searchJson: unknown, objectNumber: string): string | null {
  const rows: SearchRow[] =
    (searchJson as { response?: { rows?: SearchRow[] } })?.response?.rows ?? [];
  const mediaOf = (r: SearchRow) =>
    r.content?.descriptiveNonRepeating?.online_media?.media ?? [];
  // Prefer the row whose identifier matches the accession exactly…
  for (const row of rows) {
    const hit = mediaOf(row).find((m) => m.idsId);
    const matches = row.content?.freetext?.identifier?.some(
      (i) => i.content === objectNumber,
    );
    if (hit?.idsId && matches) return hit.idsId;
  }
  // …else the first row that has media at all.
  for (const row of rows) {
    const hit = mediaOf(row).find((m) => m.idsId);
    if (hit?.idsId) return hit.idsId;
  }
  return null;
}

export function manifestTs(dims: Record<string, ArtDims>): string {
  return (
    "// GENERATED by scripts/art/build-art.ts — do not edit by hand.\n" +
    "export const ART_DIMS: Record<string, { w: number; h: number; widths: number[] }> = " +
    JSON.stringify(dims, null, 2) +
    ";\n"
  );
}
